Mappings := {
(Join,
	"``": "~" 
	"+1": "!" 
	"+2": "@" 
	"+3": "#" 
	"+4": "$" 
	"+5": "%" 
	"+6": "^" 
	"+7": "&" 
	"+8": "*" 
	"+9": "(" 
	"+0": ")" 
	"+-": "_" 
	"+=": "+" 
	"+,": "<" 
	"+.": ">" 
	"+\": "|"
	"+/": "?"
	"+'": """"
	"+;": ":"
	"NumpadIns": "Numpad0"
	"NumpadEnd": "Numpad1"
	"NumpadDown": "Numpad2"
	"NumpadPgDn": "Numpad3"
	"NumpadLeft": "Numpad4"
	"NumpadClear": "Numpad5"
	"NumpadRight": "Numpad6"
	"NumpadHome": "Numpad7"
	"NumpadUp": "Numpad8"
	"NumpadPgUp": "Numpad9"
	"Enter": "Return"
	"Backspace": "BS" 
)}

